//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrashLocalizationWebsite2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Botes_llenos
    {
        public int id { get; set; }
        public double capacidad { get; set; }
        public string fecha { get; set; }
        public int id_bote { get; set; }
    
        public virtual Bote Bote { get; set; }
    }
}
