//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrashLocalizationWebsite2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bote
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bote()
        {
            this.Botes_llenos = new HashSet<Botes_llenos>();
        }
    
        public int id { get; set; }
        public Nullable<int> lugar { get; set; }
        public Nullable<int> categoria { get; set; }
    
        public virtual Categoria Categoria1 { get; set; }
        public virtual Lugare Lugare { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Botes_llenos> Botes_llenos { get; set; }
    }
}
