//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrashLocalizationWebsite2.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BotesEntities1 : DbContext
    {
        public BotesEntities1()
            : base("name=BotesEntities1")
        {
        }
    
        public virtual DbSet<Bote> Botes { get; set; }
        public virtual DbSet<Botes_llenos> Botes_llenos { get; set; }
        public virtual DbSet<Categoria> Categorias { get; set; }
        public virtual DbSet<Lugare> Lugares { get; set; }
        public virtual DbSet<database_firewall_rules> database_firewall_rules { get; set; }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Bote>().ToTable("Botes");
            modelBuilder.Entity<Botes_llenos>().ToTable("Botes_llenos");
            modelBuilder.Entity<Categoria>().ToTable("Categorias");
            modelBuilder.Entity<Lugare>().ToTable("Lugares");
        }
    }
}
